### ISSUE TITLE
Node.js 12 not supported

### ISSUE THREAD

**Issue by ScharV** [mcfisto/homebridge-homepod-radio#12]
I have updated the Node version on mi Raspberry to Node.js 12. Since upgrading your plugin doesn‘t work and more.
I deleted and tried to reinstall but it also won‘t work.
Would it be possible to fix it?

**Comment by DJay-X** [comment]
@ScharV I appreciate the time and work you are investing. Any chance to have an update of your plugin to work with node 12.x now that we have come to 12.6.0 ?
Thank you so much in advance. Wouldn't want to miss you plugin.

```
airtunes.target.mk:113: die Regel für Ziel „Release/obj.target/airtunes/src/codec.o“ scheiterte
make: *** [Release/obj.target/airtunes/src/codec.o] Fehler 1
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-airtunes-radio/node_modules/airtunes2/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.42-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-airtunes-radio/node_modules/airtunes2
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airtunes2@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airtunes2@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-07T17_18_48_697Z-debug.log
```

**Comment by DJay-X** [comment]
@mcfisto   I appreciate the time and work you are investing. Any chance to have an update of your plugin to work with node 12.x now that we have come to 12.6.0 ?
Thank you so much in advance. Wouldn't want to miss your plugin.

RunKit https://npm.runkit.com/homebridge-airtunes-radio point to

```
Error: Cannot find module 'lame'
Require stack:
- /app/available_modules/1562520675000/homebridge-airtunes-radio/lib/HomePodPlayer.js
- /app/available_modules/1562520675000/homebridge-airtunes-radio/lib/HomePodRadioPlatform.js
- /app/available_modules/1562520675000/homebridge-airtunes-radio/index.js
- /app/index.js
at Module._resolveFilename in core internal/modules/cjs/loader.js — line 625
at Module._load in core internal/modules/cjs/loader.js — line 527
at Module.require in core internal/modules/cjs/loader.js — line 683
at require in core internal/modules/cjs/helpers.js — line 16
```


```
airtunes.target.mk:113: die Regel für Ziel „Release/obj.target/airtunes/src/codec.o“ scheiterte
make: *** [Release/obj.target/airtunes/src/codec.o] Fehler 1
make: Verzeichnis „/usr/local/lib/node_modules/homebridge-airtunes-radio/node_modules/airtunes2/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.42-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-airtunes-radio/node_modules/airtunes2
gyp ERR! node -v v12.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airtunes2@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the airtunes2@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-07T17_18_48_697Z-debug.log
```

**Comment by IGI2** [comment]
Please update it to support Node.js 12.

It is/was a very unique plugin, it's a pity to waste such plugin.

**Comment by DJay-X** [comment]
@mcfisto Always sad to loose a Plugin due to missing ongoing development and not response from the developer to it's plans.
However, node 13.x and the lack that this plugin is not maintained anymore was the sad reason to uninstall it. :( Unfortunately without any alternative.
